<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Company.proto

namespace App\Modules\Invoices\Api\GeneratedDtos\Metadata;

class Company
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
œ
Company.protoIngenious.Invoice"’
Company

id (	
name (	
street (	
city (	
zip (	
phone (	
email (	
	createdAt (
	updatedAt	 (B[Ê&App\\Modules\\Invoices\\Api\\GeneratedDtosâ/App\\Modules\\Invoices\\Api\\GeneratedDtos\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

