<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InvoiceProductLine.proto

namespace App\Modules\Invoices\Api\GeneratedDtos\Metadata;

class InvoiceProductLine
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \App\Modules\Invoices\Api\GeneratedDtos\Metadata\Product::initOnce();
        $pool->internalAddGeneratedFile(
            '
†
InvoiceProductLine.protoIngenious.Invoice"r
InvoiceProductLine

id (	+
product (2.Ingenious.Invoice.Product
quantity (
	createdAt (B[Ê&App\\Modules\\Invoices\\Api\\GeneratedDtosâ/App\\Modules\\Invoices\\Api\\GeneratedDtos\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

