<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoice.proto

namespace App\Modules\Invoices\Api\GeneratedDtos\Metadata;

class Invoice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \App\Modules\Invoices\Api\GeneratedDtos\Metadata\ApprovalStatus::initOnce();
        \App\Modules\Invoices\Api\GeneratedDtos\Metadata\Company::initOnce();
        \App\Modules\Invoices\Api\GeneratedDtos\Metadata\InvoiceProductLine::initOnce();
        $pool->internalAddGeneratedFile(
            '
ù
Invoice.protoIngenious.InvoiceCompany.protoInvoiceProductLine.proto"Æ
Invoice

id (	
number (	
	issueDate (	
dueDate (	1
status (2!.Ingenious.Invoice.ApprovalStatus
	createdAt (
	updatedAt (2
issuingCompany (2.Ingenious.Invoice.Company1
billedCompany	 (2.Ingenious.Invoice.Company;
productLines
 (2%.Ingenious.Invoice.InvoiceProductLineB[Ê&App\\Modules\\Invoices\\Api\\GeneratedDtosâ/App\\Modules\\Invoices\\Api\\GeneratedDtos\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

