<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Product.proto

namespace App\Modules\Invoices\Api\GeneratedDtos\Metadata;

class Product
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ù
Product.protoIngenious.Invoice"p
Product

id (	
name (	
bruttoPrice (
currency (	
	updatedAt (
	createdAt (B[Ê&App\\Modules\\Invoices\\Api\\GeneratedDtosâ/App\\Modules\\Invoices\\Api\\GeneratedDtos\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

