<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ApprovalStatus.proto

namespace App\Modules\Invoices\Api\GeneratedDtos;

use UnexpectedValueException;

/**
 * Protobuf type <code>Ingenious.Invoice.ApprovalStatus</code>
 */
class ApprovalStatus
{
    /**
     * Generated from protobuf enum <code>draft = 0;</code>
     */
    const draft = 0;
    /**
     * Generated from protobuf enum <code>approved = 1;</code>
     */
    const approved = 1;
    /**
     * Generated from protobuf enum <code>rejected = 2;</code>
     */
    const rejected = 2;

    private static $valueToName = [
        self::draft => 'draft',
        self::approved => 'approved',
        self::rejected => 'rejected',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

