<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InvoiceProductLine.proto

namespace App\Modules\Invoices\Api\GeneratedDtos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * Represents one billed product with it's quantity on the invoice
 *
 * Generated from protobuf message <code>Ingenious.Invoice.InvoiceProductLine</code>
 */
class InvoiceProductLine extends \Google\Protobuf\Internal\Message
{
    /**
     * UUID of this line
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Billed product
     *
     * Generated from protobuf field <code>.Ingenious.Invoice.Product product = 2;</code>
     */
    protected $product = null;
    /**
     * Quantity of the product
     *
     * Generated from protobuf field <code>int32 quantity = 3;</code>
     */
    protected $quantity = 0;
    /**
     * unix timestamp in seconds of creation of the record of this line
     *
     * Generated from protobuf field <code>int64 createdAt = 4;</code>
     */
    protected $createdAt = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           UUID of this line
     *     @type \App\Modules\Invoices\Api\GeneratedDtos\Product $product
     *           Billed product
     *     @type int $quantity
     *           Quantity of the product
     *     @type int|string $createdAt
     *           unix timestamp in seconds of creation of the record of this line
     * }
     */
    public function __construct($data = NULL) {
        \App\Modules\Invoices\Api\GeneratedDtos\Metadata\InvoiceProductLine::initOnce();
        parent::__construct($data);
    }

    /**
     * UUID of this line
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * UUID of this line
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Billed product
     *
     * Generated from protobuf field <code>.Ingenious.Invoice.Product product = 2;</code>
     * @return \App\Modules\Invoices\Api\GeneratedDtos\Product|null
     */
    public function getProduct()
    {
        return $this->product;
    }

    public function hasProduct()
    {
        return isset($this->product);
    }

    public function clearProduct()
    {
        unset($this->product);
    }

    /**
     * Billed product
     *
     * Generated from protobuf field <code>.Ingenious.Invoice.Product product = 2;</code>
     * @param \App\Modules\Invoices\Api\GeneratedDtos\Product $var
     * @return $this
     */
    public function setProduct($var)
    {
        GPBUtil::checkMessage($var, \App\Modules\Invoices\Api\GeneratedDtos\Product::class);
        $this->product = $var;

        return $this;
    }

    /**
     * Quantity of the product
     *
     * Generated from protobuf field <code>int32 quantity = 3;</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Quantity of the product
     *
     * Generated from protobuf field <code>int32 quantity = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * unix timestamp in seconds of creation of the record of this line
     *
     * Generated from protobuf field <code>int64 createdAt = 4;</code>
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * unix timestamp in seconds of creation of the record of this line
     *
     * Generated from protobuf field <code>int64 createdAt = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->createdAt = $var;

        return $this;
    }

}

