<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoice.proto

namespace App\Modules\Invoices\Api\GeneratedDtos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ingenious.Invoice.Invoice</code>
 */
class Invoice extends \Google\Protobuf\Internal\Message
{
    /**
     * UUID of the invoice
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Number of the invoice in the document
     *
     * Generated from protobuf field <code>string number = 2;</code>
     */
    protected $number = '';
    /**
     * YYYY-MM-DD issue date of the invoice
     *
     * Generated from protobuf field <code>string issueDate = 3;</code>
     */
    protected $issueDate = '';
    /**
     * YYYY-MM-DD due date of the invoice
     *
     * Generated from protobuf field <code>string dueDate = 4;</code>
     */
    protected $dueDate = '';
    /**
     * Status of the invoice approval
     *
     * Generated from protobuf field <code>.Ingenious.Invoice.ApprovalStatus status = 5;</code>
     */
    protected $status = 0;
    /**
     * unix timestamp in seconds of the creation of the invoice record
     *
     * Generated from protobuf field <code>int64 createdAt = 6;</code>
     */
    protected $createdAt = 0;
    /**
     * unix timestamp in seconds of the last update of the invoice record
     *
     * Generated from protobuf field <code>int64 updatedAt = 7;</code>
     */
    protected $updatedAt = 0;
    /**
     * Company that issued the invoice
     *
     * Generated from protobuf field <code>.Ingenious.Invoice.Company issuingCompany = 8;</code>
     */
    protected $issuingCompany = null;
    /**
     * Company that is billed by the invoice
     *
     * Generated from protobuf field <code>.Ingenious.Invoice.Company billedCompany = 9;</code>
     */
    protected $billedCompany = null;
    /**
     * List of product lines of the invoice
     *
     * Generated from protobuf field <code>repeated .Ingenious.Invoice.InvoiceProductLine productLines = 10;</code>
     */
    private $productLines;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           UUID of the invoice
     *     @type string $number
     *           Number of the invoice in the document
     *     @type string $issueDate
     *           YYYY-MM-DD issue date of the invoice
     *     @type string $dueDate
     *           YYYY-MM-DD due date of the invoice
     *     @type int $status
     *           Status of the invoice approval
     *     @type int|string $createdAt
     *           unix timestamp in seconds of the creation of the invoice record
     *     @type int|string $updatedAt
     *           unix timestamp in seconds of the last update of the invoice record
     *     @type \App\Modules\Invoices\Api\GeneratedDtos\Company $issuingCompany
     *           Company that issued the invoice
     *     @type \App\Modules\Invoices\Api\GeneratedDtos\Company $billedCompany
     *           Company that is billed by the invoice
     *     @type array<\App\Modules\Invoices\Api\GeneratedDtos\InvoiceProductLine>|\Google\Protobuf\Internal\RepeatedField $productLines
     *           List of product lines of the invoice
     * }
     */
    public function __construct($data = NULL) {
        \App\Modules\Invoices\Api\GeneratedDtos\Metadata\Invoice::initOnce();
        parent::__construct($data);
    }

    /**
     * UUID of the invoice
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * UUID of the invoice
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Number of the invoice in the document
     *
     * Generated from protobuf field <code>string number = 2;</code>
     * @return string
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Number of the invoice in the document
     *
     * Generated from protobuf field <code>string number = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->number = $var;

        return $this;
    }

    /**
     * YYYY-MM-DD issue date of the invoice
     *
     * Generated from protobuf field <code>string issueDate = 3;</code>
     * @return string
     */
    public function getIssueDate()
    {
        return $this->issueDate;
    }

    /**
     * YYYY-MM-DD issue date of the invoice
     *
     * Generated from protobuf field <code>string issueDate = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIssueDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->issueDate = $var;

        return $this;
    }

    /**
     * YYYY-MM-DD due date of the invoice
     *
     * Generated from protobuf field <code>string dueDate = 4;</code>
     * @return string
     */
    public function getDueDate()
    {
        return $this->dueDate;
    }

    /**
     * YYYY-MM-DD due date of the invoice
     *
     * Generated from protobuf field <code>string dueDate = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDueDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->dueDate = $var;

        return $this;
    }

    /**
     * Status of the invoice approval
     *
     * Generated from protobuf field <code>.Ingenious.Invoice.ApprovalStatus status = 5;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Status of the invoice approval
     *
     * Generated from protobuf field <code>.Ingenious.Invoice.ApprovalStatus status = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \App\Modules\Invoices\Api\GeneratedDtos\ApprovalStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * unix timestamp in seconds of the creation of the invoice record
     *
     * Generated from protobuf field <code>int64 createdAt = 6;</code>
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * unix timestamp in seconds of the creation of the invoice record
     *
     * Generated from protobuf field <code>int64 createdAt = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->createdAt = $var;

        return $this;
    }

    /**
     * unix timestamp in seconds of the last update of the invoice record
     *
     * Generated from protobuf field <code>int64 updatedAt = 7;</code>
     * @return int|string
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * unix timestamp in seconds of the last update of the invoice record
     *
     * Generated from protobuf field <code>int64 updatedAt = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->updatedAt = $var;

        return $this;
    }

    /**
     * Company that issued the invoice
     *
     * Generated from protobuf field <code>.Ingenious.Invoice.Company issuingCompany = 8;</code>
     * @return \App\Modules\Invoices\Api\GeneratedDtos\Company|null
     */
    public function getIssuingCompany()
    {
        return $this->issuingCompany;
    }

    public function hasIssuingCompany()
    {
        return isset($this->issuingCompany);
    }

    public function clearIssuingCompany()
    {
        unset($this->issuingCompany);
    }

    /**
     * Company that issued the invoice
     *
     * Generated from protobuf field <code>.Ingenious.Invoice.Company issuingCompany = 8;</code>
     * @param \App\Modules\Invoices\Api\GeneratedDtos\Company $var
     * @return $this
     */
    public function setIssuingCompany($var)
    {
        GPBUtil::checkMessage($var, \App\Modules\Invoices\Api\GeneratedDtos\Company::class);
        $this->issuingCompany = $var;

        return $this;
    }

    /**
     * Company that is billed by the invoice
     *
     * Generated from protobuf field <code>.Ingenious.Invoice.Company billedCompany = 9;</code>
     * @return \App\Modules\Invoices\Api\GeneratedDtos\Company|null
     */
    public function getBilledCompany()
    {
        return $this->billedCompany;
    }

    public function hasBilledCompany()
    {
        return isset($this->billedCompany);
    }

    public function clearBilledCompany()
    {
        unset($this->billedCompany);
    }

    /**
     * Company that is billed by the invoice
     *
     * Generated from protobuf field <code>.Ingenious.Invoice.Company billedCompany = 9;</code>
     * @param \App\Modules\Invoices\Api\GeneratedDtos\Company $var
     * @return $this
     */
    public function setBilledCompany($var)
    {
        GPBUtil::checkMessage($var, \App\Modules\Invoices\Api\GeneratedDtos\Company::class);
        $this->billedCompany = $var;

        return $this;
    }

    /**
     * List of product lines of the invoice
     *
     * Generated from protobuf field <code>repeated .Ingenious.Invoice.InvoiceProductLine productLines = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProductLines()
    {
        return $this->productLines;
    }

    /**
     * List of product lines of the invoice
     *
     * Generated from protobuf field <code>repeated .Ingenious.Invoice.InvoiceProductLine productLines = 10;</code>
     * @param array<\App\Modules\Invoices\Api\GeneratedDtos\InvoiceProductLine>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProductLines($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Modules\Invoices\Api\GeneratedDtos\InvoiceProductLine::class);
        $this->productLines = $arr;

        return $this;
    }

}

