<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Product.proto

namespace App\Modules\Invoices\Api\GeneratedDtos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ingenious.Invoice.Product</code>
 */
class Product extends \Google\Protobuf\Internal\Message
{
    /**
     * UUID of the product
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Name of the product
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Price brutto of the product
     *
     * Generated from protobuf field <code>int32 bruttoPrice = 3;</code>
     */
    protected $bruttoPrice = 0;
    /**
     * Currency code of the product
     *
     * Generated from protobuf field <code>string currency = 4;</code>
     */
    protected $currency = '';
    /**
     * Unix timestamp in seconds of the last update of the record
     *
     * Generated from protobuf field <code>int64 updatedAt = 5;</code>
     */
    protected $updatedAt = 0;
    /**
     * Unix timestamp in seconds of the creation of the record
     *
     * Generated from protobuf field <code>int64 createdAt = 6;</code>
     */
    protected $createdAt = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           UUID of the product
     *     @type string $name
     *           Name of the product
     *     @type int $bruttoPrice
     *           Price brutto of the product
     *     @type string $currency
     *           Currency code of the product
     *     @type int|string $updatedAt
     *           Unix timestamp in seconds of the last update of the record
     *     @type int|string $createdAt
     *           Unix timestamp in seconds of the creation of the record
     * }
     */
    public function __construct($data = NULL) {
        \App\Modules\Invoices\Api\GeneratedDtos\Metadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * UUID of the product
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * UUID of the product
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Name of the product
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of the product
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Price brutto of the product
     *
     * Generated from protobuf field <code>int32 bruttoPrice = 3;</code>
     * @return int
     */
    public function getBruttoPrice()
    {
        return $this->bruttoPrice;
    }

    /**
     * Price brutto of the product
     *
     * Generated from protobuf field <code>int32 bruttoPrice = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBruttoPrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->bruttoPrice = $var;

        return $this;
    }

    /**
     * Currency code of the product
     *
     * Generated from protobuf field <code>string currency = 4;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Currency code of the product
     *
     * Generated from protobuf field <code>string currency = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Unix timestamp in seconds of the last update of the record
     *
     * Generated from protobuf field <code>int64 updatedAt = 5;</code>
     * @return int|string
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Unix timestamp in seconds of the last update of the record
     *
     * Generated from protobuf field <code>int64 updatedAt = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->updatedAt = $var;

        return $this;
    }

    /**
     * Unix timestamp in seconds of the creation of the record
     *
     * Generated from protobuf field <code>int64 createdAt = 6;</code>
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Unix timestamp in seconds of the creation of the record
     *
     * Generated from protobuf field <code>int64 createdAt = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->createdAt = $var;

        return $this;
    }

}

